<?php
// $Id$

/**
 * @file
 * Features Plumber module.
 */

require_once('features_plumber.crud.inc');

/**
 * Implementation of hook_menu().
 */
function features_plumber_menu() {
  $items = array();

  $items['features-plumber-ahah'] = array(
    'title' => 'Features Plumber AHAH Callback',
    'description' => 'AHAH callback to remove components from a feature.',
    'page callback' => 'features_plumber_form_ahah_callback',
    'access callback' => 'user_access',
    'access arguments' => array('administer features'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function features_plumber_menu_alter(&$items) {
  $items['admin/build/features/export/populate']['page callback'] = 'features_plumber_export_build_form_populate';
}

function features_plumber_export_build_form_populate() {
  $form_state = array('storage' => NULL, 'submitted' => FALSE);
  $form_build_id = $_POST['form_build_id'];

  if ($form = form_get_cache($form_build_id, $form_state)) {
    module_load_include('inc', 'features', 'features.export');
    $submitted = $_POST;
    $module_name = isset($form['#feature']->name) ? $form['#feature']->name : $form_build_id;

    $stub = array();

    // Assemble the combined component list
    $components = array_keys(features_get_components());
    foreach ($components as $component) {
      // User-selected components take precedence.
      if (!empty($submitted['sources'][$component])) {
        // Validate and set the default value for each selected option. This
        foreach ($submitted['sources'][$component] as $key => $value) {
          if (isset($form['export']['sources'][$component]['#options'][$key])) {
            $form['export']['sources'][$component]['#default_value'][$key] = $value;
          }
        }
        $stub[$component] = features_dom_decode_options(array_filter($submitted['sources'][$component]));
      }
      // Only fallback to an existing feature's values if there are no export options for the component.
      else if (!isset($form['export']['sources'][$component]) && !empty($form['#feature']->info['features'][$component])) {
        $stub[$component] = $form['#feature']->info['features'][$component];
      }
    }

    // Assemble dependencies
    $dependencies = isset($submitted['sources']['dependencies']) ? $submitted['sources']['dependencies'] : array();

    // Generate populated feature
    $export = features_populate($stub, $dependencies, $module_name);

    $output = drupal_get_form('features_plumber_form', $export, $stub, $module_name);

    $form['export']['features']['#value'] = $output;

    // Re-cache form. This ensures that if the form fails to validate, selected
    // values are preserved for the user.
    form_set_cache($submitted['form_build_id'], $form, $form_state);

    $output .= features_plumber_ahah_js();
    $output .= theme('status_messages');

    drupal_json(array('status' => TRUE, 'data' => $output));
    exit;
  }
  drupal_json(array('status' => FALSE, 'data' => ''));
  exit;
}

/**
 * Helper function to pull all the ahah js and output it cleanly.
 */
function features_plumber_ahah_js() {
  // For inline Javascript to validate as XHTML, all Javascript containing
  // XHTML needs to be wrapped in CDATA. To make that backwards compatible
  // with HTML 4, we need to comment out the CDATA-tag.
  $embed_prefix = "\n<!--//--><![CDATA[//><!--\n";
  $embed_suffix = "\n//--><!]]>\n";
  $js = drupal_add_js();
  $data = $js['setting'];
  $output = '';

  foreach ($data as $key => $value) {
    if (!isset($value['ahah'])) {
      unset($data[$key]);
    }
  }

  if (!empty($data)) {
    $output = '<script type="text/javascript">';
    $output .= $embed_prefix;
    $output .= 'jQuery.extend(Drupal.settings, ';
    $output .= drupal_to_js(call_user_func_array('array_merge_recursive', $data));
    $output .= ");";
    $output .= $embed_suffix;
    $output .= "</script>\n";
  }

  return $output;
}

function features_plumber_form($form_state, $export, $stub, $feature) {
  $form = array();
  $form['features_plumber']['#tree'] = TRUE;

  $form['#feature'] = $feature;

  $form['ahah-results'] = array(
    '#type' => 'markup',
    '#value' => '<div id="features-plumber-ahah-results">&nbsp;</div>',
  );

  $components = $export['features'];
  $components['dependencies'] = $export['dependencies'];

  $records = features_plumber_records_load_by_feature($feature);

  foreach ($components as $component => $component_vals) {
    if (features_plumber_component_is_supported($component)) {
      foreach ($component_vals as $component_val) {
        if (!in_array($component_val, $stub[$component])) {
          $name = features_plumber_generate_name($feature, $component, $component_val);
          $default_value = !isset($records[$name]); // Backwards!
          $element = features_plumber_record_form_element($component, $component_val, $default_value);
          //$element = form_expand_ahah($element);
          $form['features_plumber'][$component][$component_val] = $element;
        }
      }
    }
  }

  $form['components'] = array(
    '#type' => 'markup',
    '#value' => theme('features_plumber_components', $export, $stub),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#attributes' => array(
      'style' => 'display: none;',
    ),
  );

  return $form;
}

function features_plumber_form_ahah_callback() {
  $form_state = array('storage' => NULL, 'submitted' => FALSE);
  $form_build_id = $_POST['form_build_id'];

  if ($form = form_get_cache($form_build_id, $form_state)) {
    $args = $form['#parameters'];
    $form_id = array_shift($args);
    $form['#post'] = $_POST;
    $form['#redirect'] = FALSE;
    $form['#programmed'] = FALSE;
    $form_state['post'] = $_POST;
    drupal_process_form($form_id, $form, $form_state);
    $feature = $form['#feature'];

    foreach ($form_state['values']['features_plumber'] as $component => $array) {
      foreach ($array as $component_val => $keep) {
        $t_args = array(
          '@feature' => $feature,
          '@component' => $component,
          '@component-val' => $component_val,
        );

        if (!$keep) {
          drupal_set_message('Saving');
          if (!features_plumber_record_create($feature, $component, $component_val)) {
            drupal_set_message('There was a problem saving @component/@component-val to feature @feature.');
          }
        }
      }
    }

    $form = drupal_rebuild_form($form_id, $form_state, $args, $form_build_id);

    drupal_json(array('status' => TRUE, 'data' => theme('status_messages')));
    exit;
  }
  drupal_json(array('status' => FALSE, 'data' => ''));
  exit;
}

function theme_features_plumber_form($form) {
  return drupal_render($form);
}

/**
 * Implementation of hook_theme().
 */
function features_plumber_theme() {
  $items = array();

  $items['features_plumber_components'] = 
  $items['features_plumber_component_list'] = array();
  $items['features_plumber_form'] = array(
    'arguments' => array('form' => NULL),
  );

  return $items;
}

function features_plumber_theme_registry_alter(&$items) {
  $items['features_components']['function'] = 'theme_features_plumber_components';
}

/**
 * Theme a set of features export components.
 */
function theme_features_plumber_components($info, $sources = array()) {
  $output = '';
  $rows = array();
  $components = features_get_components();
  if (!empty($info['features']) || !empty($info['dependencies']) || !empty($sources)) {
    $export = array_unique(array_merge(
      array_keys($info['features']),
      array_keys($sources),
      array('dependencies')
    ));
    foreach ($export as $component) {
      if ($component === 'dependencies') {
        $feature_items = isset($info[$component]) ? $info[$component] : array();
      }
      else {
        $feature_items = isset($info['features'][$component]) ? $info['features'][$component] : array();
      }
      $source_items = isset($sources[$component]) ? $sources[$component] : array();
      if (!empty($feature_items) || !empty($source_items)) {
        $rows[] = array(array(
          'data' => isset($components[$component]['name']) ? $components[$component]['name'] : $component,
          'header' => TRUE
        ));
        $rows[] = array(array(
          'data' => theme('features_plumber_component_list', $feature_items, $source_items, array(), $component),
          'class' => 'component'
        ));
      }
    }
    $output .= theme('table', array(), $rows);
    $output .= theme('features_component_key');
  }
  return $output;
}

/**
 * Theme individual components in a component list.
 */
function theme_features_plumber_component_list($components, $source = array(), $conflicts = array(), $component) {
  $list = array();

  foreach ($components as $key => $component_val) {
    if (!in_array($component_val, $source)) {
      $id = "$component:$component_val";
      $attributes = array('class' => 'features-detected');
      if (features_plumber_component_is_supported($component)) {
        $attributes['class'] .= ' features-plumber-plumbable';
        $attributes['component'] = $component;
        $attributes['component_val'] = $component_val;
      }
      $list[] = '<span'. drupal_attributes($attributes) .'>'. check_plain($component_val) ."</span>";
    }
    elseif (is_array($conflicts) && in_array($component_val, $conflicts)) {
      $list[] = "<span class='features-conflict'>". check_plain($component_val) ."</span>";
    }
    else {
      $list[] = "<span class='features-source'>". check_plain($component_val) ."</span>";
    }
  }

  foreach ($source as $component_val) {
    // If a source component is no longer in the items, it was removed because
    // it is provided by a dependency.
    if (!in_array($component_val, $components)) {
      $list[] = "<span class='features-dependency'>". check_plain($component_val) ."</span>";
    }
  }

  return "<span class='features-component-list'>". implode(' ', $list) ."</span>";
}

function features_plumber_component_is_supported($component) {
  return in_array($component, features_plumber_supported_components());
}

function features_plumber_supported_components() {
  return array(
    'views',
    'variable',
    'context',
    'content',
    'dependencies',
  );
}

function features_plumber_record_form_element($component, $component_val, $default_value) {
  return array(
    '#type' => 'checkbox',
    '#default_value' => $default_value,
    '#ahah' => array(
      'path' => 'features-plumber-ahah',
      'wrapper' => 'features-plumber-ahah-results', //'features-export-populated',
    ),
    '#attributes' => array(
      'component' => $component,
      'component_val' => $component_val,
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function features_plumber_form_features_export_form_alter(&$form, $form_state) {
  if (variable_get('features_plumber_hide_component', TRUE)) {
    unset($form['export']['components']['#options']['features_plumber']);
  }
  drupal_add_js(drupal_get_path('module', 'features_plumber') .'/features_plumber.js');
  array_unshift($form['buttons']['submit']['#submit'], 'features_plumber_export_form_submit');

  /*
  // Set the feature name to the build id if it doesn't exist.
  $feature_name = isset($form['#feature']->name) ? $form['#feature']->name : $form['#build_id'];
  $records = features_plumber_records_load_by_feature($feature);

  drupal_add_js(drupal_get_path('module', 'features_plumber') .'/features_plumber.js');
  $form['features_plumber']['#tree'] = TRUE;

  foreach ($form['export']['sources'] as $component => $element) {
    if (features_plumber_component_is_supported($component)) {
      foreach ($element['#options'] as $key => $label) {
        //$form['features_plumber'][$component][$key] = features_plumber_record_form_element($component, $key, $label);
      }
    }
  }
  */
}

function features_plumber_export_form_submit($form, &$form_state) {
  dpm($form_state);
}

/**
 * Implements hook_features_export_alter().
 */
function features_plumber_features_export_alter(&$export, $module_name) {
  if (isset($_POST['form_id']) && $_POST['form_id'] == 'features_export_form' && !isset($module_name)) {
    //$module_name = $_POST['form_build_id'];
  }

  if (!isset($module_name)) {
    return;
  }

  $cleanup = array();
  foreach (features_plumber_records_load_by_feature($module_name) as $record) {
    if (empty($module_name) || $module_name == $record->feature) {
      // If this is a depencency, we need a different part of the $export array.
      if ($record->component == 'dependencies') {
        $array = &$export['dependencies'];
      }
      elseif (isset($export['features'][$record->component])) {
        $array = &$export['features'][$record->component];
      }
      else {
        continue;
      }

      if (isset($array[$record->component_val])) {
        unset($array[$record->component_val]);
        $cleanup[$record->component] = TRUE;
        $export['features']['features_plumber'][$record->name] = $record->name;
      }
    }
  }

  if (!isset($export['features']['features_plumber'])) {
    $cleanup['features_plumber'] = TRUE;
  }
  // Make sure these guys are here.
  else {
    $export['dependencies']['features_plumber'] = 'features_plumber';
    ctools_features_export(array('features_plumber'), $export, $module_name);
  }

  foreach (array_keys($cleanup) as $component) {
    $function = "features_plumber_export_{$component}_cleanup";
    if (function_exists($function)) {
      $function($export, $module_name);
    }
  }
}

/**
 * Cleanup after Views removals.
 */
function features_plumber_export_views_cleanup(&$export) {
  if (empty($export['features']['views'])) {
    unset($export['features']['views'], $export['features']['views_api'], $export['dependencies']['views']);
  }
}

/**
 * Cleanup after Features Plumber removal.
 */
function features_plumber_export_features_plumber_cleanup(&$export) {
  if (empty($export['features']['features_plumber'])) {
    unset($export['dependencies']['features_plumber'], $export['features']['ctools']['features_plumber:features_plumber_records:1']);
  }
}

/**
 * Helper function to unset a value from an array, if it exists.
 */
function _features_plumber_array_search_unset($value, &$array) {
  // Now that we have our array, unset as needed.
  $key = array_search($value, $array);
  if ($key !== FALSE) {
    // Since we're unsetting something, we should go through at the end and
    // do any necessary cleanup.
    //unset($array[$key]);
    return TRUE;
  }
  return FALSE;
}